### ISSUE TITLE
Run the project

### ISSUE THREAD

**Issue by Megha-Navsoft** [BillBarry/pyQBWC#1]
Hi,
  Sorry for the lame question but can you please guide me on how to get this project running? What are the requirements for this? 
I have QuickBooks Desktop Pro, QuickBooks SDK and QuickBooks Web Connector installed on my machine. Is anything else needed? 
I am absolutely clueless about the desktop version of QuickBooks.
Any help will be appreciated.

**Comment by knoxvilledatabase** [comment]
Hi,
I have successfully got this project up and running and communicating with Quickbooks Desktop. What is it you are trying to accomplish?

**Comment by Megha-Navsoft** [comment]
> Hi,
> I have successfully got this project up and running and communicating with Quickbooks Desktop. What is it you are trying to accomplish?

I have basically very less idea about QB Desktop. So when I came around your project and read about QBWC, I installed it. I also have QB Desktop Pro 2018. 
So how do I run your project?

**Comment by knoxvilledatabase** [comment]
You have to build an XML Soap interface and configure the PYQWC server and Quickbooks Desktop to communicate with that interface.  The specific configuration really depends on which tables in Quickbooks you are trying to access or modify.

**Comment by Megha-Navsoft** [comment]
> You have to build an XML Soap interface and configure the PYQWC server and Quickbooks Desktop to communicate with that interface. The specific configuration really depends on which tables in Quickbooks you are trying to access or modify.

Alright. I have to figure out how to build a SOAP server.
Thanks for replying

**Comment by BillBarry** [comment]
I have not done this in a while, but I would be glad to go through it step by step with you and make sure everything is still working. It is a bit of a complicated beast to get working and probably needs some updating.  The soap server is built into pyqwc so you don't need to build one or really know what it is doing. The main part you need to replace is the client that creates the XML request.  The XML request requires a little knowledge of the Quickbooks SDK and knowledge of exactly what you are trying to accomplish.

**Comment by Megha-Navsoft** [comment]
> I have not done this in a while, but I would be glad to go through it step by step with you and make sure everything is still working. It is a bit of a complicated beast to get working and probably needs some updating. The soap server is built into pyqwc so you don't need to build one or really know what it is doing. The main part you need to replace is the client that creates the XML request. The XML request requires a little knowledge of the Quickbooks SDK and knowledge of exactly what you are trying to accomplish.

I am done with the online version of QuickBooks. So I do have an idea how QuickBooks works. But when I come to the desktop version, I'm completely lost. Even when I came across your project, I found it a bit difficult to understand what is happening. 
If it would not be a bother, kindly help me with this. At the moment any sort of request sent to QB is fine with me. It seems you have done the invoice part in your project, that is fine with me to kick start. 
So can you please tell me which file should I run here to get this project interact with QB?
